### ISSUE TITLE
How can I connect to KNX Virtual?

### ISSUE THREAD

**Issue by mortiy** [dufourgilles/knx-ip#9]
I'm trying to connect to KNX Virtual setup via: `knxClient.startDiscovery("127.0.0.1");`, but getting this error:
```
Error: send ENETUNREACH 224.0.23.12:3671
    at doSend (dgram.js:683:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
    at afterDns (dgram.js:629:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'send',
  address: '224.0.23.12',
  port: 3671
}
```
Anyone was lucky enough to make this work?

**Comment by dufourgilles** [comment]
Why did you pick the loopback IP ?
Seems like we can't send multicast message on the loopback.
Can you try with a physical interface ?

**Comment by mortiy** [comment]
Yes, physical interface IP helped. Thanks.

> Why did you pick the loopback IP ?
I was just following the IP address from here.
![image](https://user-images.githubusercontent.com/251992/91299154-dc50e600-e7a9-11ea-808a-542167d96e35.png)

**Comment by dufourgilles** [comment]
OK. Good to know.
Just in case, as you know the IP and port, you can skip the discovery part and just open the tunnel immediately.

**Comment by dufourgilles** [comment]
BTW.  Didn't know there was a KNX Virtual App.  I did request it and I'm going to start testing.
Also, I developed this KNX-IP lib because I use it in a bigger project that includes a server to control, monitor, ... entire house.  All in Typescript. And I use it for my own house since last year.  It controls all the blinds, records all the sensor info and graphs them, ... I will publish a free version of the backend server in the near future with possibility to buy the GUI
